# Dotfiles directory
export DOTFILES="$HOME/.dotfiles"  

# ZSH
ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$DOTFILES/zsh/custom"

# Plugins
plugins=(
  git
)

# Theme
ZSH_THEME="spaceship"

# Oh my zsh
source $ZSH/oh-my-zsh.sh

# nvm
export NVM_DIR="$DOTFILES/node/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# python
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
